Add more info allow list
mulesoft/docs-service-mesh pull request #118
Opened 2020-09-07 17:17 UTC by tbruno

Explain each address that needs to be added to the allow list.
Change terminology from whitelist to allow list.

2020-09-07 17:20 UTC, dosten requested changes

2020-09-07 17:20 UTC, dosten commented on modules/ROOT/pages/prepare-to-install-service-mesh.adoc
> +|*US*|*exchange-files.anypoint.mulesoft.com* |  443| Required to download the docker images that make up the Anypoint Service Mesh product
I don't think this is correct

2020-09-07 17:20 UTC, dosten commented on modules/ROOT/pages/prepare-to-install-service-mesh.adoc
> +|*EU*|*eu1.anypoint.mulesoft.com* | 443| Anypoint
`Required to connect with the control plane`?

2020-09-07 17:20 UTC, dosten commented on modules/ROOT/pages/prepare-to-install-service-mesh.adoc
> +|*US*|*exchange-files.anypoint.mulesoft.com* |  443| Required to download the docker images that make up the Anypoint Service Mesh product
`Required to download policies`?

2020-09-07 17:20 UTC, dosten commented on modules/ROOT/pages/prepare-to-install-service-mesh.adoc
> +|*ALL*|*get.helm.sh* | 443| Required to retrieve and install Helm on the Kubernetes clusters.
This seems wrong, we don't install Helm into the cluster, only into the users's machine

2020-09-07 17:20 UTC, dosten commented on modules/ROOT/pages/prepare-to-install-service-mesh.adoc
> +|*ALL*|*storage.googleapis.com* | 443| Required to retrieve and install kubectl on the Kubernetes clusters.
Same here

2020-09-07 20:36 UTC, tbruno commented
Thanks for the feedback, feedback applied @dosten

2020-09-08 19:25 UTC, dhirsch1 approved these changes

2020-09-09 23:13 UTC, dosten approved these changes

2020-09-10 18:54 UTC, merged